---
kind: ConfigMap
apiVersion: v1
metadata:
  name: javajmxconfig
  namespace: myapp
data:
  config.yaml: |
    ---
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
      - pattern: ".*"
