{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "java-springboot-app",
    "namespace": "myapp",
    "labels": {
      "app": "javaapp"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "3"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "javaapp"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "javaapp"
        },
        "annotations": {
          "prometheus.io/path": "/metrics",
          "prometheus.io/port": "5000",
          "prometheus.io/scrape": "true"
        }
      },
      "spec": {
        "volumes": [
          {
            "name": "jmx-config",
            "configMap": {
              "name": "javajmxconfig",
              "defaultMode": 420
            }
          }
        ],
        "containers": [
          {
            "name": "javacontainer",
            "image": "mdshoaib707/jmx:latest",
            "command": [
              "bash"
            ],
            "args": [
              "-c",
              "java -javaagent:/app1/jmx_prometheus_javaagent-0.2.0.jar=5000:/app1/jmxconfig/config.yaml -jar /app1/spring-boot-web-jsp-1.0.war"
            ],
            "ports": [
              {
                "name": "webport",
                "containerPort": 8080,
                "protocol": "TCP"
              }
            ],
            "resources": {
              "limits": {
                "cpu": "250m",
                "memory": "256Mi"
              },
              "requests": {
                "cpu": "250m",
                "memory": "256Mi"
              }
            },
            "volumeMounts": [
              {
                "name": "jmx-config",
                "mountPath": "/app1/jmxconfig"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 55,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2018-02-28T12:42:19Z",
        "lastTransitionTime": "2018-02-28T09:26:52Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"java-springboot-app-66dc465d75\" has successfully progressed."
      },
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-03-05T00:23:29Z",
        "lastTransitionTime": "2018-03-05T00:23:29Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
