---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alert.rules: |-
    ## alert.rules ##

    #
    # CPU Alerts
    #
    ALERT HighCPU
      IF ((sum(node_cpu{mode=~"user|nice|system|irq|softirq|steal|idle|iowait"}) by (instance, job)) - ( sum(node_cpu{mode=~"idle|iowait"}) by (instance,job) )   )   /  (sum(node_cpu{mode=~"user|nice|system|irq|softirq|steal|idle|iowait"}) by (instance, job)) * 100 > 95
      FOR 10m
      LABELS { service = "backend" }
      ANNOTATIONS {
        summary = "High CPU Usage",
        description = "This machine  has really high CPU usage for over 10m",
      }

    #
    # TPS Alerts
    #
    ALERT TPS
      IF (tomcat_threadpool_connectioncount) > 0
      FOR 1s
      LABELS {
        severity="critical"
      }
    ANNOTATIONS {
      value = "{{ $value }}",
      SUMMARY = "{{$labels.instance}} TPS",
      DESCRIPTION = "{{$labels.instance}}: TPS is greater to 0 (current value is: {{ $value }})"
    }


    #
    # DNS Lookup failures
    #
    ALERT DNSLookupFailureFromPrometheus
      IF prometheus_dns_sd_lookup_failures_total > 5
      FOR 1m
      LABELS { service = "frontend" }
      ANNOTATIONS {
        summary = "Prometheus reported over 5 DNS lookup failure",
        description = "The prometheus unit reported that it failed to query the DNS.  Look at the kube-dns to see if it is having any problems",
      }


